export const EdgeCases = {
    Bahamas: "The Bahamas",
    "Bajo Nuevo Bank": "Bajo Nuevo Bank (Petrel Is.)",
    "Bosnia Herzegovina": "Bosnia and Herzegovina",
    "Bosnia-Herzegovina": "Bosnia and Herzegovina",
    BVI: "British Virgin Islands",
    CAR: "Central African Republic",
    Curacao: "Curaçao",
    "Democratic Republic of Congo": "Democratic Republic of the Congo",
    "Guantanamo Bay": "US Naval Base Guantanamo Bay",
    "Hong Kong": "Hong Kong S.A.R.",
    "Cote D’Ivoire": "Ivory Coast",
    "Côte d’Ivoire": "Ivory Coast",
    "Macao": "Macao S.A.R",
    Micronesia: "Federated States of Micronesia",
    "Republic of the Congo": "Republic of Congo",
    "St Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St Lucia": "Saint Lucia",
    "St. Lucia": "Saint Lucia",
    "St Martin": "Saint Martin",
    "St. Martin": "Saint Martin",
    "St Pierre and Miquelon": "Saint Pierre and Miquelon",
    "St. Pierre and Miquelon": "Saint Pierre and Miquelon",
    "St Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Tanzania": "United Republic of Tanzania",
    "Timor-Leste": "East Timor",
    Serbia: "Republic of Serbia",
    Uae: "United Arab Emirates",
    UAE: "United Arab Emirates",
    Uk: "United Kingdom",
    UK: "United Kingdom",
    "US Minor Outlying Islands": "United States Minor Outlying Islands",
    "US Virgin Islands": "United States Virgin Islands",
    "United States": "United States of America",
    Us: "United States of America",
    US: "United States of America",
    Usa: "United States of America",
    USA: "United States of America"
}